services:
  mongo: 
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)'",
        ]
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 10s
      start_interval: 2s
    networks:
      - inner
      - outer
  broker:
    image: p4010/miroscic
    hostname: broker
    ports:
      - "9090:9090"
      - "9091:9091"
      - "9092:9092"
    command: broker -d -n eth0
    volumes:
      - type: bind
        source: .
        target: /root
    networks:
      - inner
      - outer
  logger:
    image: p4010/miroscic
    command: logger -s tcp://broker:9092 -m mongodb://mongo:27017
    depends_on:
      broker:
        condition: service_started
      mongo:
        condition: service_healthy
    networks:
      - inner

networks:
  inner:
    internal: true
  outer:
  